### ISSUE TITLE
How to use https?

### ISSUE THREAD

**Issue by gombru** [patrickfuller/python-js-bridge#1]
The bridge with http works, but I need https. How can I use it?

**Comment by patrickfuller** [comment]
Short answer is [here](https://stackoverflow.com/questions/18307131/how-to-create-https-tornado-server). Switch out `Application` for `HTTPServer` and reference your keypair.

Longer answer is that HTTPS isn't one size fits all, and your [SSL Labs](https://www.ssllabs.com/ssltest/) score will take some work. A more modern approach to SSL is to route through an Nginx reverse proxy with a LetsEncrypt certificate, which there are many tutorials on. Also, I wrote this library when websockets were new, and a lot has simplified since. You may want to instead use something like [aiohttp](https://aiohttp.readthedocs.io/en/stable/) for your HTTP server.

**Comment by gombru** [comment]
Thanks @patrickfuller. I solved it using HTTPServer. I'm having trouble with my SSL certificate now, but that's another story. 
Closing.
